name: flutter_course
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  #basics
  http: ^0.13.4
  path: ^1.8.0
  path_provider: ^2.0.5
  connectivity: ^3.0.6
  uuid: ^3.0.4
  crypto: ^3.0.1
  shared_preferences: ^2.0.8 
  lottie: ^1.2.1
  flutter_native_splash: ^1.2.4
  flutter_launcher_icons: ^0.9.2
  font_awesome_flutter: ^9.1.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  dio: ^4.0.0
  intl: ^0.17.0
  recase: ^4.0.0
  flutter_windowmanager: ^0.2.0
  fl_chart: ^0.40.2
  #ui
  liquid_swipe: ^2.1.0  
  curved_navigation_bar: ^1.0.1
  flutter_zoom_drawer: ^2.1.1
  overlay_support: ^1.2.1
  fluttertoast: ^8.0.8
  introduction_screen: ^2.1.0
  flutter_signin_button: ^2.0.0
  sign_button: ^2.0.1
  shimmer: ^2.0.0
  flutter_blurhash: ^0.6.0
  blurhash: ^1.0.0
  carousel_slider: ^4.0.0
  settings_ui: ^1.0.0
  numberpicker: ^2.1.1
  bubble: ^1.2.1
  slide_to_act: ^2.0.1
  like_button: ^2.0.3
  animations: ^2.0.2
  story_view: ^0.13.1
  photo: ^0.4.8
  #payments
  flutter_credit_card: ^3.0.1
  purchases_flutter: ^3.4.6
  in_app_purchase: ^1.0.9
  #firebase/ google
  firebase_storage: ^10.0.4
  firebase_core : ^1.7.0
  firebase_messaging: ^10.0.8
  cloud_firestore: ^2.5.3 
  firebase_auth: ^3.1.3
  google_sign_in: ^5.1.1
  twitter_login: ^4.0.1
  flutter_facebook_auth: "^3.5.0"
  flutter_local_notifications: ^9.0.0
  google_maps_flutter: ^2.0.11
  sign_in_with_apple: ^3.0.0
  googleapis: ^6.0.0
  google_mobile_ads: ^0.13.5
  #tools
  image_cropper: ^1.4.1
  image_picker: ^0.8.2
  flutter_image_compress: ^1.0.0
  file_picker: ^4.1.3
  flutter_pdfview: ^1.2.1
  #camera: ^0.9.4+1
  url_launcher: ^6.0.12
  flutter_webview_plugin: ^0.4.0
  webview_flutter: ^2.1.1
  location: ^4.3.0
  flutter_polyline_points: ^1.0.0
  cached_network_image: ^3.1.0
  flutter_easyloading: ^3.0.3
  sn_progress_dialog: ^1.0.3
  uni_links: ^0.5.1
  package_info: ^2.0.2
  store_redirect: ^2.0.0
  flutter_audio_recorder2: ^0.0.2
  video_player: ^2.2.5
  just_audio: ^0.9.13
  flutter_vibrate: ^1.3.0
  in_app_review: ^2.0.3
  devicelocale: ^0.5.0
  open_mail_app: ^0.3.0
  web_browser: ^0.5.0
  webviewx: ^0.2.1
  widget_mask: ^0.1.1
  gallery_saver: ^2.3.2
  local_auth: ^1.1.8
  share: ^2.0.4
  flutter_chat_ui: ^1.5.0
  flutter_firebase_chat_core: ^1.5.0
  flutter_chat_types: ^3.2.0
  flutter_link_previewer: ^2.6.0
  photo_view: ^0.13.0
  camera_camera: ^2.0.2
  camera_web: ^0.2.1+1
  double_back_to_close_app: ^2.0.1
  open_file: ^3.2.1
  dropdown_search: ^2.0.0
  #end

  #story_view: ^0.13.1
  #social_media_widgets: ^1.0.0+2 #snap dismiss

  #story_designer: ^1.0.0
  #text_editor: ^0.4.0
  story_creator: ^1.0.0

  #zoom_pinch_overlay: ^1.1.2
  #zoom_widget: ^0.2.1

  #tiktoklikescroller: ^0.1.8
  #photofilters: ^3.0.1

  #camera_camera: ^2.0.2
  #wechat_assets_picker: ^6.2.3
  
  
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  image_path: "assets/icon.png"
  #image_path_ios: "assets/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_foreground: "assets/icon_foreground.png"
  adaptive_icon_background: "#ffffff"

flutter_native_splash:
  color: "#000A0C"
  color_dark: "#000A0C"
  image: "assets/splash.png"
  image_dark: "assets/splash.png"
  android: true
  ios: true
  #android_gravity: fill
  #ios_contenet_mode: scaleAspectFill

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
